### ISSUE TITLE
Debug errors in Test Setup

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/easy-digital-downloads-plugin#17]
Turn on debug mode and run Test Setup, it will show various warnings. Cover these cases atleast:

- Successful test Setup
- No Xpub address present
- User account disabled
- Multiple xpubs / incorrect callback error

**Comment by DarrenWestwood** [comment]
* Successful test Setup - ```Notice: Undefined property: stdClass::$message in /var/www/html/wpspeedtest/wp-content/plugins/edd-blockonomics/php/Blockonomics.php on line 34```
* No Xpub address present - ```Notice: Undefined offset: 0 in /var/www/html/wpspeedtest/wp-content/plugins/edd-blockonomics/edd-blockonomics.php on line 363```
```Notice: Trying to get property 'callback' of non-object in /var/www/html/wpspeedtest/wp-content/plugins/edd-blockonomics/edd-blockonomics.php on line 363```
* User account disabled - ```Notice: Undefined property: stdClass::$address in /var/www/html/wpspeedtest/wp-content/plugins/edd-blockonomics/php/Blockonomics.php on line 35```
* Multiple xpubs / incorrect callback error - No errors
