### ISSUE TITLE
TestSetup Not working with Wordpress 5.3.2

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/easy-digital-downloads-plugin#24]
Fails at [this line](https://github.com/blockonomics/easy-digital-downloads-plugin/blob/master/edd-blockonomics.php#L576). Probably because jquery is not imported in EDD settings. Please fix by using non jquery calls

Also I am not sure why [this line](https://github.com/blockonomics/easy-digital-downloads-plugin/blob/master/edd-blockonomics.php#L578) is needed. Remove if not relevant

**Comment by blockonomics** [comment]
Verified Fix
