### ISSUE TITLE
sanitize_key is  converting addr to lower_case

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/easy-digital-downloads-plugin#26]
Found this in Wordpres 5.4.1   + EDD 2.9.23

Suggest a fix for this. Also theoretically it should be affecting our woocommerce plugin as well. Check why or why not ?

**Comment by shivaenigma** [comment]
This is the reasons for it being not able to find addr in orders array

**Comment by jusasiiv** [comment]
> Suggest a fix for this

Looks like `sanitize_key` is used to sanitize REQUEST parameters. The actual intended function of `sanitize_key` is according to [wp documentation](https://developer.wordpress.org/reference/functions/sanitize_key/): _Sanitizes a string key. Keys are used as internal identifiers_ but we are not using keys here.

Two alternate solutions:
1) Use `htmlspecialchars()` like WHMCS plugin does to sanitize REQUEST params
or
2) Create our own version of `sanitize_key` https://core.trac.wordpress.org/browser/tags/5.4/src/wp-includes/formatting.php#L2132 by dropping the `strtolower()`

>Also theoretically it should be affecting our woocommerce plugin as well. Check why or why not ?

WooCommerce plugin does not use `sanitize_key` so it is not affected
