### ISSUE TITLE
No Altcoin or Flyp.me support

### ISSUE THREAD

**Issue by avoxismith** [blockonomics/easy-digital-downloads-plugin#7]
No Flyp.me support available for Altcoins as compared to the woocommerce plugin. It says on the overview page the altcoin payments supported.

**Comment by blockonomics** [comment]
Try updates regarding https://github.com/cnu1439/easy-digital-downloads-plugin/issues/4 here

**Comment by shivaenigma** [comment]
Fixed in version 1.3. Please update to latest blockonomics edd plugin from store
